
### Raise a new format alarm
POST http://{{host}}:8080/fm/v1.0/event
Content-Type: application/json

{
    "event": {
        "commonEventHeader": {
            "version": "4.1", "vesEventListenerVersion": "7.2", "domain": "fault",
            "eventName": "Fault_Vscf:Acs-Ericcson_PilotNumberPoolExhaustion", "eventId": "TA00001", "sequence": 4,
            "priority": "HIGH", "reportingEntityId": "cc305d54-75b4-431b-adb2-eb6b9e541234",
            "reportingEntityName": "ibcx0001vm002oam001", "sourceId": "de305d54-75b4-431b-adb2-eb6b9e546014",
            "sourceName": "scfx0001vm002cap001", "nfVendorName": "Viettel", "nfNamingCode": "scfx",
            "nfcNamingCode": "ssc", "startEpocchMicrosec": 1413578172123456, "lastEpochMicrosec": 1413378172655555,
            "timeZoneOffset": "UTC+07:00"
        }, "faultFields": {
            "faultFieldsVersion": 4.0, "alarmCondition": "PilotNumberPoolExhaustion", "eventSourceType": "other",
            "specificProblem": "Calls cannot complete - pilot numbers are unavailable", "eventSeverity": "CRITICAL",
            "vfStatus": "Active", "alarmAdditionalInformation": {
                "PilotNumberPoolSize": "1000", "OtherParam": "1000"
            }
        }
    }
}

### Raise a new format alarm
POST http://{{host}}:8080/fm/alarmreport
Content-Type: application/json

{

}

### event old format
POST http://{{host}}:8080/fm/eventreport
Content-Type: application/json

[
    {
        "ne_type": "GNODEB", "ne": "gNB0208HgNB", "event_id": "9100", "keygen": "9100_DU\/CELL(1)",
        "node_name": "gNB0208HgNB", "trigger_time": "1606319383000", "location": "DU\/CELL(1)",
        "probable_cause": "Cell Start Success"
    }
]
