GET http://{{host}}:8090/subjects

###
GET http://{{host}}:8081/subjects/{{subject}}/versions

###
GET http://{{host}}:8081/subjects/{{subject}}/versions/latest/schema

###
POST http://{{host}}:8081/subjects/{{subject}}/versions
Content-Type: application/json

{
    "schema": "syntax = \"proto3\";\npackage org.onap.ves;\n\noption java_package = \"org.onap.ves\";\noption java_outer_classname = \"EventKey\";\n\nmessage Key {\n  string eventId = 1;\n  string sourceId = 2;\n  int64 initialInstant = 3;\n}",
    "schemaType": "PROTOBUF"
}

###
DELETE http://{{host}}:8081/subjects/{{subject}}/versions/?permanent=true
