spring:
  application:
    name: ems.fm
  profiles:
    active: production
    include:
      - db
  main:
    web-application-type: reactive
  webflux:
    base-path: /fm
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000

server:
  port: 8090
  tomcat:
    accept-count: 250
    max-connections: 2048
    threads:
      max: 300
      min-spare: 100

  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
